nodeLinker: node-modules
packageExtensions:
  "@feathersjs/authentication@*":
    peerDependencies:
      typescript: "*"
  "@feathersjs/koa@*":
    peerDependencies:
      typescript: "*"
  "@types/react-tabs@*":
    peerDependencies:
      react: "*"
  "@typescript-eslint/utils@5.62.0":
    peerDependencies:
      typescript: "*"
  "dmg-builder@*":
    peerDependencies:
      electron-builder-squirrel-windows: "*"
  "electron-builder-squirrel-windows@*":
    peerDependencies:
      dmg-builder: "*"
  "electron-builder@*":
    peerDependencies:
      electron-builder-squirrel-windows: "*"